# Generated by Django 5.2.6 on 2026-04-06 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id_preferencia', models.AutoField(primary_key=True, serialize=False)),
                ('idioma', models.CharField(default='es', max_length=20)),
                ('tema', models.CharField(default='claro', max_length=20)),
                ('autoplay', models.BooleanField(default=True)),
                ('recibir_notificaciones', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
