# Generated by Django 5.2.6 on 2026-05-03 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentoDestacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_video', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('canal', models.ForeignKey(db_column='id_canal', on_delete=django.db.models.deletion.CASCADE, related_name='momentos_destacados', to='canales.canal')),
            ],
            options={
                'verbose_name': 'Momento destacado',
                'verbose_name_plural': 'Momentos destacados',
                'db_table': 'momentos_destacados',
            },
        ),
    ]
