# Generated by Django 5.2.6 on 2026-05-03 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de canal',
                'verbose_name_plural': 'Tipos de canal',
                'db_table': 'tipos_canal',
            },
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario_propietario', models.IntegerField()),
                ('nombre_canal', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('foto_canal', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_canal', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_canal', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_canal', models.ForeignKey(db_column='id_tipo_canal', on_delete=django.db.models.deletion.PROTECT, related_name='canales', to='canales.tipocanal')),
            ],
            options={
                'verbose_name': 'Canal',
                'verbose_name_plural': 'Canales',
                'db_table': 'canales',
            },
        ),
    ]
