# Generated by Django 5.2.6 on 2026-04-12 22:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperacionPassword',
            fields=[
                ('id_recuperacion', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('expiracion', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
