# Generated by Django 5.2.6 on 2026-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0002_recuperacionpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
