# Generated by Django 5.2.6 on 2026-05-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("canales", "0001_initial"),
        ("categorias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado", models.CharField(choices=[("programado", "Programado"), ("en_vivo", "En vivo"), ("finalizado", "Finalizado")], default="programado", max_length=20)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("calidad_actual", models.CharField(blank=True, max_length=30, null=True)),
                ("destacado", models.BooleanField(default=False)),
                ("canal", models.ForeignKey(db_column="id_canal", on_delete=django.db.models.deletion.CASCADE, related_name="streams", to="canales.canal")),
                ("categoria", models.ForeignKey(db_column="id_categoria", on_delete=django.db.models.deletion.PROTECT, related_name="streams", to="categorias.categoria")),
            ],
            options={
                "verbose_name": "Stream",
                "verbose_name_plural": "Streams",
                "db_table": "streams",
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionStream",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("resolucion", models.CharField(default="720p", max_length=20)),
                ("bitrate", models.IntegerField(default=2500)),
                ("latencia_modo", models.CharField(default="normal", max_length=30)),
                ("audio_activo", models.BooleanField(default=True)),
                ("stream", models.OneToOneField(db_column="id_stream", on_delete=django.db.models.deletion.CASCADE, related_name="configuracion", to="streams.stream")),
            ],
            options={
                "verbose_name": "Configuracion de stream",
                "verbose_name_plural": "Configuraciones de stream",
                "db_table": "configuraciones_stream",
            },
        ),
    ]
